export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
/*export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';*/

export const LOAD_CLASSES_SUCCESS = 'LOAD_CLASSES_SUCCESS';
export const CREATE_CLASS_SUCCESS = 'CREATE_CLASS_SUCCESS';
export const DELETE_CLASS_SUCCESS = 'DELETE_CLASS_SUCCESS';

/*member types*/
export const LOAD_MEMBERS_SUCCESS = 'LOAD_MEMBERS_SUCCESS';
export const CREATE_MEMBER_SUCCESS = 'CREATE_MEMBER_SUCCESS';
export const UPDATE_MEMBER_SUCCESS = 'UPDATE_MEMBER_SUCCESS';

/*badges types*/
export const LOAD_BADGES_SUCCESS = 'LOAD_BADGES_SUCCESS';
export const CREATE_BADGE_SUCCESS = 'CREATE_BADGE_SUCCESS';
export const DELETE_BADGE_SUCCESS = 'DELETE_BADGE_SUCCESS';

/*Styles types*/
export const LOAD_STYLES_SUCCESS = 'LOAD_STYLES_SUCCESS';
export const CREATE_STYLE_SUCCESS = 'CREATE_STYLE_SUCCESS';
export const DELETE_STYLE_SUCCESS = 'DELETE_STYLE_SUCCESS';

/*Grades types*/
export const LOAD_GRADES_SUCCESS = 'LOAD_GRADES_SUCCESS';
export const CREATE_GRADES_SUCCESS = 'CREATE_GRADES_SUCCESS';
export const DELETE_GRADES_SUCCESS = 'DELETE_GRADES_SUCCESS';